module.exports = {
    verbose: false,
    testEnvironment: 'jsdom',
    transform: {
        '^.+\\.ts(x)?$': 'babel-jest',
        '^.+\\.svg$': '<rootDir>/__test__/transform/svg.js',
        '^(?!.*\\.json$)': '<rootDir>/__test__/transform/file.js',
    },
    transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$'],
    roots: ['<rootDir>/src'],
    moduleNameMapper: {
        '\\.css$': 'identity-obj-proxy',
        '@/api(.*)': '<rootDir>/src/api/$1',
        '@/assets(.*)': '<rootDir>/src/assets/$1',
        '@/components(.*)': '<rootDir>/src/components/$1',
        '@/UI(.*)': '<rootDir>/src/components/UI/$1',
        '@/data(.*)': '<rootDir>/src/data/$1',
        '@/store(.*)': '<rootDir>/src/store/$1',
        '@/types(.*)': '<rootDir>/src/types/$1',
        '@/utils(.*)': '<rootDir>/src/utils/$1',
        '@/distributors(.*)': '<rootDir>/src/utils/distributors/$1',
        '@/enums(.*)': '<rootDir>/src/utils/enums/$1',
        '@/helpers(.*)': '<rootDir>/src/utils/helpers/$1',
        '@/hooks(.*)': '<rootDir>/src/utils/hooks/$1',
        '@/mocks(.*)': '<rootDir>/src/utils/mocks/$1',
        '@/__test__(.*)$': '<rootDir>/src/__test__/$1',
    },
    moduleFileExtensions: [
        'js',
        'jsx',
        'ts',
        'tsx',
    ],
    testMatch: ['<rootDir>/src/**/*.{spec,test}.{ts,tsx}'],
    clearMocks: true,
    collectCoverage: true,
    collectCoverageFrom: [
        'src/**/*.{ts,tsx}',
        '!src/**/*.d.ts',
        '!src/index.{ts,tsx}',
        '!src/store/index.{ts,tsx}',
        '!src/**/*.stories.{ts,tsx}',
        '!src/pages/*.{ts,tsx}',
        '!src/pages/**/*.{ts,tsx}',
        '!src/__test__/**/*',
        '!src/utils/animations/**/*',
        '!src/utils/distributors/**/*',
        '!src/utils/enums/**/*',
        '!src/utils/mocks/**/*',
        '!src/types/*',
        '!src/types/**/*',
        '!src/**/types/*',
        '!src/**/data/*',
    ],
    coverageDirectory: './__test__/coverage',
    coverageReporters: ['html', 'lcov'],
    setupFiles: ['<rootDir>/src/__test__/setup.ts', 'jest-canvas-mock'],
    setupFilesAfterEnv: ['<rootDir>/src/__test__/mockSetup.ts'],
    snapshotSerializers: ['jest-serializer-html'],
    globals: {'babel-jest': {tsconfig: '<rootDir>/tsconfig.test.json'}},
};
