name: GitGuardian
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{github.event.before}}
          GITHUB_PUSH_BASE_SHA: ${{github.event.base}}
          GITHUB_PULL_BASE_SHA: ${{github.event.pull_request.base.sha}}
          GITHUB_DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
          GITGUARDIAN_API_KEY: ${{secrets.GITGUARDIAN_API_KEY}}
