name: Playwright
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn --frozen-lockfile --check-files
      - run: npx playwright install --with-deps
      - run: yarn test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: report
          path: report/
          retention-days: 30
